[package]
name = "hydra"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
git2 = "0.19.0"
home = "0.5.9"
serde = { version = "1.0.210", features = ["derive"] }
tabled = "0.16.0"
toml = "0.8.19"
