name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - base

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install mdBook
      run: |
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C /usr/local/bin

    - name: Build the book
      run: mdbook build ./book

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        external_repository: Annrtl/Edifice_book
        publish_dir: ./book/book
